# File size limit
max_file_size_kb: 1024  # Files larger than 1MB will be ignored

# Exclusions for content reading
exclude:
  # Extensions to ignore for content reading
  extensions:
    - .env
    - .pyc
    - .log
    - .git
    - .gitignore

  # Specific files to ignore for content reading
  files:
    - LICENSE
    - file_inutile.txt

# Exclusions for XML structure
exclude_structure:
  # Extensions to ignore in the XML structure
  extensions:
    - .pdf
    - .png
    - .jpg
    - .jpeg
  # Folders to ignore in the XML structure
  directories:
    - __pycache__
    - .git
    - venv
  # Specific files to ignore in the XML structure
  files:
    - LICENSE