# Limite dimensione file
max_file_size_kb: 1024  # Files più grandi di 1MB verranno ignorati

# Esclusioni per la lettura del contenuto
exclude:
  # Estensioni da ignorare per la lettura del contenuto
  extensions:
    - .env
    - .pyc
    - .log
    - .git
    - .gitignore

  # File specifici da ignorare per la lettura del contenuto
  files:
    - LICENSE
    - file_inutile.txt

# Esclusioni per la struttura XML
exclude_structure:
  # Estensioni da ignorare nella struttura XML
  extensions:
    - .pdf
    - .png
    - .jpg
    - .jpeg
  # Cartelle da ignorare nella struttura XML
  directories:
    - __pycache__
    - .git
    - venv
  # File specifici da ignorare nella struttura XML
  files:
    - LICENSE